// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterNetSpeed():Promise<string>;

export function GetSysInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;
