// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {functions} from '../models';

export function GetCPUStats():Promise<functions.CPUStats>;

export function GetInterNetSpeed():Promise<string>;

export function GetMemoryStats():Promise<functions.MemoryStats>;

export function GetSysInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;
