// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {functions} from '../models';

export function CheckCleanerPermissions():Promise<functions.PermissionStatus>;

export function CheckInternetConnection():Promise<boolean>;

export function CleanSelectedFiles(arg1:Array<functions.FileInfo>):Promise<{[key: string]: any}>;

export function GetBatteryDetails():Promise<string>;

export function GetCPUStats():Promise<functions.CPUStats>;

export function GetFormattedSize(arg1:number):Promise<string>;

export function GetInterNetSpeed():Promise<string>;

export function GetMemoryStats():Promise<functions.MemoryStats>;

export function GetSysInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ScanCleanableFiles():Promise<functions.CleanerResult>;

export function ScanSafeCleanableFiles():Promise<functions.CleanerResult>;
