// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterNetSpeed() {
  return window['go']['main']['App']['GetInterNetSpeed']();
}

export function GetSysInfo() {
  return window['go']['main']['App']['GetSysInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
