// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInternetConnection() {
  return window['go']['main']['App']['CheckInternetConnection']();
}

export function GetCPUStats() {
  return window['go']['main']['App']['GetCPUStats']();
}

export function GetInterNetSpeed() {
  return window['go']['main']['App']['GetInterNetSpeed']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetSysInfo() {
  return window['go']['main']['App']['GetSysInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
