// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCleanerPermissions() {
  return window['go']['main']['App']['CheckCleanerPermissions']();
}

export function CheckInternetConnection() {
  return window['go']['main']['App']['CheckInternetConnection']();
}

export function CleanSelectedFiles(arg1) {
  return window['go']['main']['App']['CleanSelectedFiles'](arg1);
}

export function GetBatteryDetails() {
  return window['go']['main']['App']['GetBatteryDetails']();
}

export function GetCPUStats() {
  return window['go']['main']['App']['GetCPUStats']();
}

export function GetFormattedSize(arg1) {
  return window['go']['main']['App']['GetFormattedSize'](arg1);
}

export function GetInterNetSpeed() {
  return window['go']['main']['App']['GetInterNetSpeed']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetSysInfo() {
  return window['go']['main']['App']['GetSysInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ScanCleanableFiles() {
  return window['go']['main']['App']['ScanCleanableFiles']();
}

export function ScanSafeCleanableFiles() {
  return window['go']['main']['App']['ScanSafeCleanableFiles']();
}
